# Generated by Django 3.2.8 on 2021-10-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='usage_flag',
            field=models.CharField(db_column='usage_flag', default='1', max_length=10),
        ),
    ]
